### ISSUE TITLE
Case where opportune hauling should not occur

### ISSUE THREAD

**Issue by mvadovszki** [CodeOptimist/rimworld-jobs-of-opportunity#4]
I had a pawn far in the field (next to stone chunks), he wanted to do stonecutting but instead of taking the chunk directly next to him, he chose to opportune haul an random item to a stockpile near the workstation, then run all the way back to where he started to begin the stone-cutting task.  Any chance that this can be improved?

**Comment by CodeOptimist** [comment]
Thanks so much for the report!

For performance reasons, much of the RimWorld codebase (and other games) "satisfice" rather than "optimize". That is, they take a solution that is easy to compute and "good enough", this is done for performance because computing and sorting the entire actual choices available in order to select the best one is a much slower operation.

So unfortunately there will always be scenarios where a pawn seems to take an action that is less than ideal. 🤷‍♂️ 

Stone chunks are quite heavy, you may have also encountered a scenario where the pawn couldn't hold the heavier item.

There are a few other things that could have occurred as well.

Keep a watchful eye out and if you can consistently reproduce an odd scenario from a save game I will happily look into it. :smile:

**Comment by mvadovszki** [comment]
[haulBug.zip](https://github.com/CodeOptimist/rimworld-jobs-of-opportunity/files/4941049/haulBug.zip)

I thought it might be a fixable case, the issue is that the pawn is looking for hauling towards the workstation rather than towards the ingredients the workstation needs.

**Comment by CodeOptimist** [comment]
Dude you gave me an **amazing** save game perfectly illustrating the request and all I did was gaslight you, I'm so sorry! I finally got to looking at it today, after being very productive, and turns out I did indeed just solve this with a new "Optimize hauling ingredients" feature. I just tested your save file both before and after and yup, works!

Incredibly helpful of you, sorry for being so dismissive, from your original report I was falsely picturing a big colony and a hundred mods, a scenario I wasn't yet equipped to debug. Please do continue submitting save games with issues like this in the future, it's actually incredibly helpful and I recently put a notice on the Steam page asking for them too.
